apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: keep-a-changelog
  name: keep-a-changelog
spec:
  replicas: 1
  selector:
    matchLabels:
      run: keep-a-changelog
  strategy: {}
  template:
    metadata:
      labels:
        run: keep-a-changelog
    spec:
      containers:
      - image: nginx:alpine
        name: keep-a-changelog
        ports:
        - containerPort: 80
        resources: {}
status: {}