apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: keep-a-changelog
  name: keep-a-changelog
spec:
  replicas: 1
  selector:
    matchLabels:
      run: keep-a-changelog
  strategy: {}
  template:
    metadata:
      labels:
        run: keep-a-changelog
    spec:
      containers:
      - image: eritikass/changelog:latest
        imagePullPolicy: Always
        name: keep-a-changelog
        ports:
        - containerPort: 8080
        resources: {}
        env:
          - name: PRIVATE_KEY
            valueFrom:
              configMapKeyRef:
                name: bot-private-key
                key: changelogbot-private-key.pem
          - name: APP_ID
            valueFrom:
              configMapKeyRef:
                name: keep-a-changelog-config
                key: APP_ID
          - name: WEBHOOK_SECRET
            valueFrom:
              configMapKeyRef:
                name: keep-a-changelog-config
                key: WEBHOOK_SECRET
status: {}